#!/usr/bin/env bash
# Sync Twilio credentials into secrets/dart_defines.json and
# lib/core/config/twilio_local_secrets.dart (used by normal flutter run).
set -euo pipefail
cd "$(dirname "$0")/.."

dest="secrets/dart_defines.json"
example="secrets/dart_defines.example.json"

if [[ ! -f "$example" ]]; then
  echo "Missing template: $example" >&2
  exit 1
fi

if [[ ! -f "$dest" ]]; then
  cp "$example" "$dest"
  echo "Created $dest from template."
fi

echo ""
echo "Next steps:"
echo "  1. Edit $dest with your Twilio Account SID, Auth Token, and Verify Service SID."
echo "  2. Re-run this script to sync into lib/core/config/twilio_local_secrets.dart"
echo "  3. Stop the app, then flutter run (no dart-define needed)."
echo ""

if ! command -v python3 >/dev/null 2>&1; then
  echo "Install python3 to sync credentials into Dart."
  exit 1
fi

python3 - <<'PY'
import json
import sys
from pathlib import Path

path = Path("secrets/dart_defines.json")
data = json.loads(path.read_text())
keys = ("TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_VERIFY_SERVICE_SID")
missing = [k for k in keys if not str(data.get(k, "")).strip()]
if missing:
    print("WARNING: still empty in dart_defines.json:")
    for k in missing:
        print(f"  - {k}")
    print("Fill them, then re-run this script.")
    sys.exit(1)

sid = str(data["TWILIO_ACCOUNT_SID"]).strip().replace("'", "\\'")
token = str(data["TWILIO_AUTH_TOKEN"]).strip().replace("'", "\\'")
service = str(data["TWILIO_VERIFY_SERVICE_SID"]).strip().replace("'", "\\'")
out = Path("lib/core/config/twilio_local_secrets.dart")
out.write_text(
    "/// Generated by tool/setup_dart_defines.sh — do not commit.\n"
    "class TwilioLocalSecrets {\n"
    f"  static const accountSid = '{sid}';\n"
    f"  static const authToken = '{token}';\n"
    f"  static const serviceSid = '{service}';\n"
    "}\n"
)
print(f"OK: wrote {out}")
print("OK: all Twilio keys are set. Normal flutter run uses real OTP.")
PY
